sudo: false

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

node_js: 14.15

cache:
  directories:
    - $HOME/.cache/pip
    - node_modules

before_install:
  - pip install -U pip

install:
  - pip install -r requirements.txt
  - cd frontend && npm install
  - cd frontend && npm run build

env: 
  - FLASK_APP=./webserver.py

script:
  - python -m flask unit test