version: '3'
services:
  flaskvue:
    container_name: flaskvue
    build: .
    environment:
      # FLASK_ENV: development
      FLASK_APP: webserver.py
      FLASK_RUN_HOST: 0.0.0.0
    networks:
      - flaskvue
    restart: always

  nginx: 
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./backend/config/docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flaskvue
    links:
      - flaskvue
    ports:
      - 5000:5000
      - 443:443
    networks:
      - flaskvue
    restart: always

networks:
  flaskvue:
